In [3]:
import tensorflow as tf
sess = tf.Session()

# tf.random_uniform
    default : random_uniform[0 to 1] with the shape
    min_val, max_val to control random_unirom[min_val to 1]

In [4]:
x = tf.random_uniform([2,3])
print("x : tf.random_uniform([2,3])")
print(sess.run(x))
y = tf.random_uniform([2,3],minval=2, maxval=3)
print("y : tf.random_uniform([2,3],minval=2, maxval=3)")
print(sess.run(y))
z = tf.Variable(y)
print('tf.get_collection("variables")[-1]')
print(tf.get_collection('variables')[-1])
sess.run(tf.variables_initializer([tf.get_collection('variables')[-1]]))
print("z : tf.Variable(y)")
print(sess.run(z))

x : tf.random_uniform([2,3])
[[ 0.88049412  0.91043818  0.70566249]
 [ 0.14366758  0.62014663  0.76052034]]
y : tf.random_uniform([2,3],minval=2, maxval=3)
[[ 2.82261682  2.84427881  2.97256279]
 [ 2.3057344   2.07980633  2.79386067]]
tf.get_collection("variables")[-1]
Tensor("Variable/read:0", shape=(2, 3), dtype=float32)
z : tf.Variable(y)
[[ 2.91565013  2.93227863  2.94932938]
 [ 2.42796946  2.70552945  2.73377204]]


# tf.sign

In [7]:
x = tf.constant([[-1,2],[3,-4]],dtype = tf.float32)
print("x : tf.constant([[-1,2],[3,-4]],dtype = tf.float32)")
print(sess.run(x))
print("tf.sign(x)")
print(sess.run(tf.sign(x)))

x : tf.constant([[-1,2],[3,-4]],dtype = tf.float32)
[[-1.  2.]
 [ 3. -4.]]
tf.sign(x)
[[-1.  1.]
 [ 1. -1.]]


# tf.nn.moments

In [7]:
x = tf.constant([[3,4,5],[1,2,4]],dtype = tf.float32)
mean, var = tf.nn.moments(x,[0], name = 'hi')
print(mean)
print(var)
print(sess.run(mean))
print(sess.run(var))
print(sess.run(tf.nn.moments(x,[1],name = 'hi2')))
print(sess.run(tf.nn.moments(x,[0,1],name = 'hi2')))

Tensor("hi_4/hi_1/mean:0", shape=(3,), dtype=float32)
Tensor("hi_4/hi_1/variance:0", shape=(3,), dtype=float32)
[ 2.   3.   4.5]
[ 1.    1.    0.25]
(array([ 4.        ,  2.33333325], dtype=float32), array([ 0.66666669,  1.5555557 ], dtype=float32))
(3.1666667, 1.8055556)


# tf.range, tf.size

In [21]:
x = tf.constant([3,4,5,6])
print(sess.run(tf.size(x)))
print(sess.run(tf.range(0, tf.size(x))))
print(sess.run(tf.gather(x,[1,2,2,1])))

4
[0 1 2 3]
[4 5 5 4]


# tf.assign(ref, value, validate_shape, use_locking)
    ref : a mutable tensor variable, may be unitialized
    value : a Tensor, same time as ref the value assigned to variable
    validate shape : default true, ture the shape of 'value' matches the shape of the tensor assigned 
                    otherwise shape of 'ref' = shape of 'value'
    

In [3]:
x = tf.Variable([1.])
x_op = tf.assign(x, [2.,3.,4.], validate_shape=False)
sess.run(tf.global_variables_initializer())
print(sess.run(x_op))
print(sess.run(x))

[ 2.  3.  4.]
[ 2.  3.  4.]


# tf.control_dependencies

In [2]:
x = tf.Variable([1.])
x_op = tf.assign(x, [2.])
with tf.control_dependencies([x_op]):
    y = tf.add(x, [1.])
sess.run(tf.global_variables_initializer())
print(sess.run(y))
print(sess.run(x))

[ 3.]
[ 2.]


In [3]:
x = tf.Variable([1.])
x_op = tf.assign(x, [2.])
y = tf.add(x, [1.])
sess.run(tf.global_variables_initializer())
print(sess.run(y))
print(sess.run(x))
print(sess.run(x_op))
print(sess.run(x))
print(sess.run(y))

[ 2.]
[ 1.]
[ 2.]
[ 2.]
[ 3.]


# tf.get_default_graph

In [12]:
c = tf.constant(4.0)
print(c.graph)
print(tf.get_default_graph())

# tf.is_inf, tf.is_finite, tf.is_nan
    Must be float in tf.log

In [3]:
print(sess.run(tf.is_inf(tf.log(0.0))))
print(sess.run(tf.is_inf(tf.log(0.5))))
print(sess.run(tf.is_finite(1.0)))
print(sess.run(tf.is_nan(-tf.log(-1.0))))
print(sess.run(tf.is_nan(-tf.log(1.0))))

True
False
True
True
False


# tf.identity

In [8]:
x = tf.constant(2.0)
y = tf.identity(x)
print(sess.run(x))
print(sess.run(y))

2.0
2.0


# tf.cond

In [9]:
x = tf.constant(2)
y = tf.constant(5)
def f1(): 
    return tf.multiply(x, 17)
def f2(): 
    return tf.add(y, 23)
r = tf.cond(tf.less(x, y), f1, f2)
print(r)
print(sess.run(r))

Tensor("cond/Merge:0", shape=(), dtype=int32)
34


# tf.clip_by_value()

In [4]:
print(sess.run(tf.clip_by_value(0, clip_value_max=5, clip_value_min=3)))
print(sess.run(tf.clip_by_value(7, clip_value_max=5, clip_value_min=3)))
print(sess.run(tf.clip_by_value(4, clip_value_max=5, clip_value_min=3)))

3
5
4


# tf.train.exponential_decay() and global_step
decayed_learning_rate = learning_rate * decay_rate ^ (global_step / decay_steps)    

learning_rate:  The initial learning rate.  
global_step: Global step to use for the decay computation. Must not be negative.  
decay_steps:  Must be positive. See the decay computation above.  
decay_rate: A scalar float32 or float64 Tensor or a Python number. The decay rate.
staircase: Boolean. It True decay the learning rate at discrete intervals
name: String. Optional name of the operation. Defaults to 'ExponentialDecay'

In [2]:
x_data = [1., 2., 3.]
y_data = [1., 2., 3.]

w = tf.Variable(tf.random_uniform([1], -1.0, 1.0),name ='w')
b = tf.Variable(tf.random_uniform([1], -1.0, 1.0),name ='b')

hypothesis = w * x_data + b
cost = tf.reduce_mean(tf.square(hypothesis - y_data))
global_step = tf.Variable(0, trainable=False)
learning_rate = tf.train.exponential_decay(learning_rate= 0.1, global_step= global_step,
                                        decay_steps = 2, decay_rate = 0.96, staircase=True)

#train only w not b
var_list = []
var_list.append(tf.get_collection("trainable_variables")[0])
print("Only train_variable : {}".format(var_list[0]))

train = tf.train.GradientDescentOptimizer(learning_rate).minimize(loss = cost
                                                                  ,global_step=global_step
                                                                 ,var_list = var_list
                                                                  #,var_list = tf.get_collection("trainable_variables")
                                                                 )
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
print(sess.run(w))
print(sess.run(b))
for step in range(10):
    sess.run(train)
    print("i | global_step | learning_rate")
    print("{} |          {}|{}|".format(step, sess.run(global_step), sess.run(learning_rate)))
print(sess.run(w))
print(sess.run(b))

Only train_variable : Tensor("w/read:0", shape=(1,), dtype=float32)
[-0.18229818]
[ 0.61625671]
i | global_step | learning_rate
0 |          1|0.10000000149011612|
i | global_step | learning_rate
1 |          2|0.09600000083446503|
i | global_step | learning_rate
2 |          3|0.09600000083446503|
i | global_step | learning_rate
3 |          4|0.09216000139713287|
i | global_step | learning_rate
4 |          5|0.09216000139713287|
i | global_step | learning_rate
5 |          6|0.0884735956788063|
i | global_step | learning_rate
6 |          7|0.0884735956788063|
i | global_step | learning_rate
7 |          8|0.08493465185165405|
i | global_step | learning_rate
8 |          9|0.08493465185165405|
i | global_step | learning_rate
9 |          10|0.08153726160526276|
[ 0.73588997]
[ 0.61625671]


# tf.nn.conv2d_transpose

In [44]:
x = tf.constant([[1.,2.],[2.,6.]])
x = tf.tile(x,[2,2])
y = tf.constant([[0,1.],[0,0]])
x_r = tf.reshape(x, [1,4,4,1])
y_r = tf.reshape(y, [2,2,1,1])
print("Input : {}".format(x_r.get_shape()))
print(sess.run(x_r))
print("Filter : {}".format(y_r.get_shape()))
print(sess.run(y_r))
print(sess.run(tf.nn.conv2d_transpose(x_r, y_r, strides = [1,1,1,1], output_shape= [1,4,4,1], padding='SAME')))
#print(sess.run(tf.nn.conv2d_transpose(x_r, y_r, strides = [1,2,2,1], output_shape= [1,7,7,1], padding='SAME')))
#print(sess.run(tf.nn.conv2d_transpose(x_r, y_r, strides = [1,2,2,1], output_shape= [1,8,8,1], padding='SAME')))
#print(sess.run(tf.nn.conv2d_transpose(x_r, y_r, strides = [1,3,3,1], output_shape= [1,10,10,1], padding='SAME')))

Input : (1, 4, 4, 1)
[[[[ 1.]
   [ 2.]
   [ 1.]
   [ 2.]]

  [[ 2.]
   [ 6.]
   [ 2.]
   [ 6.]]

  [[ 1.]
   [ 2.]
   [ 1.]
   [ 2.]]

  [[ 2.]
   [ 6.]
   [ 2.]
   [ 6.]]]]
Filter : (2, 2, 1, 1)
[[[[ 0.]]

  [[ 1.]]]


 [[[ 0.]]

  [[ 0.]]]]
[[[[ 0.]
   [ 1.]
   [ 2.]
   [ 1.]]

  [[ 0.]
   [ 2.]
   [ 6.]
   [ 2.]]

  [[ 0.]
   [ 1.]
   [ 2.]
   [ 1.]]

  [[ 0.]
   [ 2.]
   [ 6.]
   [ 2.]]]]


# tf.nn.conv2d

In [18]:
x = tf.constant([[1.,2.],[2.,6.]])
x = tf.tile(x,[2,2])
y = tf.constant([[1.,0],[1.,-1]])
x_r = tf.reshape(x, [1,4,4,1])
y_r = tf.reshape(y, [2,2,1,1])
print("Input : {}".format(x_r.get_shape()))
print(sess.run(x_r))
print("Filter : {}".format(y_r.get_shape()))
print(sess.run(y_r))
print(sess.run(tf.nn.conv2d(input= x_r, filter = y_r, strides=[1,1,1,1],padding = 'SAME')))

Input : (1, 4, 4, 1)
[[[[ 1.]
   [ 2.]
   [ 1.]
   [ 2.]]

  [[ 2.]
   [ 6.]
   [ 2.]
   [ 6.]]

  [[ 1.]
   [ 2.]
   [ 1.]
   [ 2.]]

  [[ 2.]
   [ 6.]
   [ 2.]
   [ 6.]]]]
Filter : (2, 2, 1, 1)
[[[[ 1.]]

  [[ 0.]]]


 [[[ 1.]]

  [[-1.]]]]
[[[[-3.]
   [ 6.]
   [-3.]
   [ 8.]]

  [[ 1.]
   [ 7.]
   [ 1.]
   [ 8.]]

  [[-3.]
   [ 6.]
   [-3.]
   [ 8.]]

  [[ 2.]
   [ 6.]
   [ 2.]
   [ 6.]]]]


# tf.concat

In [4]:
x = tf.constant([[1.,3.,4.],[2.,5.,6.]])
print("x : {}".format(x.get_shape()))
y = tf.constant([[1.,2.],[3.,4.]])
print("y : {}".format(y.get_shape()))
z = tf.concat([x,y], 1)
print("tf.concat([x,y],1) : {}".format(z.get_shape()))
print(sess.run(z))

x : (2, 3)
y : (2, 2)
tf.concat([x,y],1) : (2, 5)
[[ 1.  3.  4.  1.  2.]
 [ 2.  5.  6.  3.  4.]]


# tf.nn.sigmoid_cross_entropy_with_logits

In [4]:
x = [[1.,3.,4.],[2.,5.,6.]]
print("x")
print(x)
x_true = [[1.,1.,0.],[0.,1.,0.]]
print("x_true")
print(x_true)
x_sigmoid = tf.sigmoid(x)
print("tf.sigmoid(x)")
print(sess.run(x_sigmoid))
print("First method")
ones = tf.ones_like(x_sigmoid)
print(-sess.run(x_true*tf.log(x_sigmoid)+(ones-x_true)*tf.log(ones-x_sigmoid)))
print("Second method")
print(sess.run(tf.nn.sigmoid_cross_entropy_with_logits(labels = x_true, logits= x)))

x
[[1.0, 3.0, 4.0], [2.0, 5.0, 6.0]]
x_true
[[1.0, 1.0, 0.0], [0.0, 1.0, 0.0]]
tf.sigmoid(x)
[[ 0.7310586   0.95257413  0.98201376]
 [ 0.88079703  0.99330717  0.99752742]]
First method
[[ 0.31326166  0.04858734  4.01814842]
 [ 2.12692761  0.00671532  6.00249338]]
Second method
[[ 0.31326169  0.04858735  4.01814985]
 [ 2.12692809  0.00671535  6.00247574]]


# normalize with tf.reduce_mean

In [19]:
x = tf.constant([[1,2,3],[4,5,6]])
y = tf.constant([2,2,2])
print(sess.run(x-y))
print(sess.run(x+[1]))
print(sess.run(x+[2,3,4]))

[[-1  0  1]
 [ 2  3  4]]
[[2 3 4]
 [5 6 7]]
[[ 3  5  7]
 [ 6  8 10]]


In [24]:
x = tf.constant([[1,2,3],[4,5,6]], dtype = tf.float32)
print("x : {}".format(sess.run(x).shape))
mean = tf.reduce_mean(x,[0])
print("mean = tf.reduce_mean(x,[0])")
print(sess.run(mean))
print("x_mean")
print(sess.run(x-mean))
std =tf.reduce_mean(tf.square(x-mean),[0])
print("std =tf.reduce_mean(tf.square(x-mean),[0])")
print(sess.run(std))

x : (2, 3)
mean = tf.reduce_mean(x,[0])
[ 2.5  3.5  4.5]
x_mean
[[-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]]
std =tf.reduce_mean(tf.square(x-mean),[0])
[ 2.25  2.25  2.25]


# tf.get_shape()

In [11]:
x = tf.constant([[1,2,3],[4,5,6]])
print("x : {}".format(x.get_shape()))
print(sess.run(x))
print("x.get_shape().ndims")
print(x.get_shape().ndims)
print("tf.expand_dims(x, dim=1).get_shape().ndims")
print(tf.expand_dims(x, dim=1).get_shape().ndims)

x : (2, 3)
[[1 2 3]
 [4 5 6]]
x.get_shape().ndims
2
tf.expand_dims(x, dim=1).get_shape().ndims
3


# tf.tile()

In [8]:
x = tf.constant([[1,2,3],[4,5,6]])
print("x : {}".format(sess.run(x).shape))
print(sess.run(x))
print("tf.tile(x,[2,3]): {}".format(sess.run(tf.tile(x,[2,3])).shape))
print(sess.run(tf.tile(x,[2,3])))

x : (2, 3)
[[1 2 3]
 [4 5 6]]
tf.tile(x,[2,3]): (4, 9)
[[1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]
 [1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]]


# tf.expand_dims

In [10]:
x = tf.constant([[1,2,3],[4,5,6]])
print("x : {}".format(sess.run(x).shape))
print(sess.run(x))
print("tf.expand_dims(x, dim=1) : {}".format(sess.run(tf.expand_dims(x, dim=1)).shape))
print(sess.run(tf.expand_dims(x, dim=1)))
print("tf.expand_dims(x, dim=0) : {}".format(sess.run(tf.expand_dims(x, dim=0)).shape))
print(sess.run(tf.expand_dims(x, dim=0)))
print("tf.expand_dims(x, dim=2) : {}".format(sess.run(tf.expand_dims(x, dim=2)).shape))
print(sess.run(tf.expand_dims(x, dim=2)))
print("tf.expand_dims(x, dim=-1) : {}".format(sess.run(tf.expand_dims(x, dim=-1)).shape))
print(sess.run(tf.expand_dims(x, dim=-1)))
'''
print("tf.expand_dims(x, dim=3) : {}".format(sess.run(tf.expand_dims(x, dim=3)).shape))
print(sess.run(tf.expand_dims(x, dim=3)))
Error occured
'''


x : (2, 3)
[[1 2 3]
 [4 5 6]]
tf.expand_dims(x, dim=1) : (2, 1, 3)
[[[1 2 3]]

 [[4 5 6]]]
tf.expand_dims(x, dim=0) : (1, 2, 3)
[[[1 2 3]
  [4 5 6]]]
tf.expand_dims(x, dim=2) : (2, 3, 1)
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
tf.expand_dims(x, dim=-1) : (2, 3, 1)
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


'\nprint("tf.expand_dims(x, dim=3) : {}".format(sess.run(tf.expand_dims(x, dim=3)).shape))\nprint(sess.run(tf.expand_dims(x, dim=3)))\nError occured\n'

# tf.stack, tf.unstack, tf.split

In [11]:
v1 = tf.constant([1,2,3])
v2 = tf.constant([4,5,6])
t = tf.stack([v1,v2])
print(sess.run(t))
print(sess.run(tf.unstack(t)))
print(sess.run(tf.split(t, 2, axis=0)))

[[1 2 3]
 [4 5 6]]
[array([1, 2, 3], dtype=int32), array([4, 5, 6], dtype=int32)]
[array([[1, 2, 3]], dtype=int32), array([[4, 5, 6]], dtype=int32)]


# tf.get_variable() v.s tf.variable

In [2]:
# Bad example of defining the name of variables
v = tf.Variable(tf.random_normal([2,3]), name='v')
v2 = tf.Variable(tf.random_normal([2,3]), name='v')

x = tf.get_variable('v', [2, 3], initializer= tf.constant_initializer(0.0))

i = 0 
while True:
    try:
        print(tf.get_collection('trainable_variables')[i])
        i+=1
    except IndexError:
        break

sess.run(tf.global_variables_initializer())

print(sess.run(v))
print(sess.run(tf.shape(v)))
print(sess.run(v2))
print(sess.run(x))

Tensor("v/read:0", shape=(2, 3), dtype=float32)
Tensor("v_1/read:0", shape=(2, 3), dtype=float32)
Tensor("v_2/read:0", shape=(2, 3), dtype=float32)
[[-0.58031696  0.24948798 -0.28777111]
 [-0.25976044 -1.17540312  2.15104508]]
[2 3]
[[-0.55646604 -0.19363521  1.92169797]
 [-0.73861814  0.67804688  0.74387604]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


 # Share variables with scope

In [4]:
with tf.variable_scope('hi') as scope:
    v = tf.get_variable('a', [2,3],initializer= tf.random_normal_initializer())
    scope.reuse_variables()
    x = tf.get_variable('a', [2,3],initializer= tf.random_normal_initializer())
    sess.run(tf.global_variables_initializer())
    print(sess.run(v))
    print(sess.run(x))
    

[[-0.30628705 -0.39645576 -0.4932133 ]
 [ 1.5868845  -0.87908548  0.93908131]]
[[-0.30628705 -0.39645576 -0.4932133 ]
 [ 1.5868845  -0.87908548  0.93908131]]


# tf.split()

In [3]:
value = tf.random_normal([5,30],stddev=0.1)
print(sess.run(tf.shape(value)))

split0, split1, split2 = tf.split(value, [4, 15, 11], 1)
print(sess.run(tf.shape(split0)))
print(sess.run(tf.shape(split1)))
print(sess.run(tf.shape(split2)))
split0, split1, split2 = tf.split(value, 3, axis=1)
print(sess.run(tf.shape(split0)))
splits = tf.split(value, 3, axis=1)
print(sess.run(tf.shape(splits)))
splits = tf.split(value, 5, axis=0)
print(sess.run(tf.shape(splits)))

[ 5 30]
[5 4]
[ 5 15]
[ 5 11]
[ 5 10]
[ 3  5 10]
[ 5  1 30]
